set nocompatible
filetype off

" Vundle stuff begin.
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'octol/vim-cpp-enhanced-highlight'
Plugin 'flazz/vim-colorschemes'
call vundle#end()
filetype plugin indent on
" Vundle stuff end.

set history=1000
set showcmd
set showmode
set gcr=a:blinkon0
set visualbell t_vb=

set colorcolumn=81

set autoread
set number
set t_Co=256
syntax on
autocmd BufNewFile,BufRead *.xtx set filetype=tex
set ruler
set hlsearch

set autoindent
set shiftwidth=4
set softtabstop=4
set tabstop=4
set backspace=2
set list listchars=tab:>-,trail:_,nbsp:.,extends:>,precedes:<
set cindent cinoptions=(0,w1,W4,L0,l1,g0 shiftwidth=4 expandtab
set cinoptions+=(0,w1

set wrap
set linebreak
set wildmode=list:longest
set wildmenu
set wildignore=*.o,*.obj,*~,DS_Store*,*.gem,*.png,*.jpg,*.gif
set scrolloff=8

"colorscheme 256-grayvim
"colorscheme antares
"colorscheme badwolf
"colorscheme benlight
"colorscheme Benokai
"colorscheme blackboard
"colorscheme blacklight
"colorscheme blaquemagick
"colorscheme blazer
"colorscheme blueprint
"colorscheme brogrammer
"colorscheme bubblegum-256-dark
"colorscheme buddy
"colorscheme burnttoast256
"colorscheme busierbee
"colorscheme busybee
"colorscheme bvemu
"colorscheme cabin
"colorscheme calmar256-dark
"colorscheme candycode

colorscheme candyman

"colorscheme CandyPaper
"colorscheme charged-256
"colorscheme Chasing_Logic
"colorscheme clue
"colorscheme cobalt2
"colorscheme CodeFactoryv3
"colorscheme colorsbox-faff
"colorscheme colorsbox-greenish
"colorscheme colorsbox-material
"colorscheme colorsbox-stblue
"colorscheme colorsbox-stbright
"colorscheme colorsbox-steighties
"colorscheme colorsbox-stnight
"colorscheme colorzone
"colorscheme cthulhian
"colorscheme d8g_01
"colorscheme d8g_03
"colorscheme dante
"colorscheme darkburn
"colorscheme deepsea
"colorscheme desertEx
"colorscheme desertink
"colorscheme detailed
"colorscheme devbox-dark-256
"colorscheme distinguished
"colorscheme dracula
"colorscheme dual
"colorscheme elise
"colorscheme elisex
"colorscheme elrond
"colorscheme eva01
"colorscheme evolution
"colorscheme flattr
"colorscheme forneus
"colorscheme frood
"colorscheme gentooish
"colorscheme getafe
"colorscheme grb256
"colorscheme gryffin
"colorscheme harlequin
"colorscheme herald
"colorscheme heroku-terminal
"colorscheme hybrid_material
"colorscheme hybrid_reverse
"colorscheme icansee
"colorscheme iceberg
"colorscheme ingretu
"colorscheme inori
"colorscheme ir_black
"colorscheme itg_flat
"colorscheme janah
"colorscheme jellybeans
"colorscheme jellyx
"colorscheme kalahari
"colorscheme kruby
"colorscheme last256
"colorscheme leo
"colorscheme lettuce
"colorscheme lilypink
"colorscheme lucid
"colorscheme luinnar
"colorscheme luna-term
"colorscheme lxvc
"colorscheme minimalist
"colorscheme mizore
"colorscheme molokai_dark
"colorscheme molokai
"colorscheme monokain
"colorscheme moonshine
"colorscheme mrkn256
"colorscheme nazca
"colorscheme neverland2-darker
"colorscheme neverland2
"colorscheme neverland-darker
"colorscheme neverland
"colorscheme oceanblack256
"colorscheme preto
"colorscheme pride
"colorscheme ps_color
"colorscheme pt_black
"colorscheme railscasts
"colorscheme rdark-terminal
"colorscheme redblack
"colorscheme Revolution
"colorscheme sadek1
"colorscheme seti
"colorscheme shobogenzo
"colorscheme smyck
"colorscheme sorcerer
"colorscheme soruby
"colorscheme sourcerer
"colorscheme southernlights
"colorscheme spacegray
"colorscheme stingray
"colorscheme strange
"colorscheme sunburst
"colorscheme synic
"colorscheme tayra
"colorscheme tchaba2
"colorscheme termschool
"colorscheme thornbird
"colorscheme thor
"colorscheme tir_black
"colorscheme Tomorrow-Night-Bright
"colorscheme Tomorrow-Night-Eighties
"colorscheme Tomorrow-Night
"colorscheme triplejelly
"colorscheme tropikos
"colorscheme twilight256
"colorscheme ubaryd
"colorscheme up
"colorscheme valloric
"colorscheme vimbrant
"colorscheme wasabi256
"colorscheme wellsokai
"colorscheme woju
"colorscheme wombat256i
"colorscheme wombat256mod
"colorscheme wombat256
"colorscheme xoria256
"colorscheme xterm16
"colorscheme zephyr
"colorscheme znake
